# Error type constants for validation and test results
SCHEMA_VALIDATION_FAILURE = "SCHEMA_VALIDATION_FAILURE"
PATTERN_DO_NOT_MATCH = "PATTERN_DO_NOT_MATCH"
WRONG_STATUS = "WRONG_STATUS"
MISSING_KEY = "MISSING_KEY"
INCORRECT_VALUE = "INCORRECT_VALUE"
